import type { ResourceLink, SettingsState, WorkItem } from "./types";

export const sampleStudioVersion = 1;

export const sampleStudioSettings: SettingsState = {
  studioName: "Northstar Post",
  profileName: "Maya Chen",
  profileUsername: "mayacuts",
  profileTitle: "Lead Editor",
  profileBio: "Editorial and post-production for creator-led brands.",
  profileLocation: "Dubai, UAE",
  profileImageUrl: "",
  publicActiveProjects: 2,
  publicDeliveredEdits: 18,
  publicTurnaroundDays: 3,
  timeZone: "Asia/Dubai",
  dateFormat: "Month Day, Year",
  weekStart: "Mon",
  currencyCode: "USD",
  customClients: ["Aperture Coffee", "Field Notes", "Orbit Labs"],
  clients: [
    { id: "client-aperture-coffee", name: "Aperture Coffee", company: "Aperture Coffee", contactName: "", email: "", phone: "", notes: "", archived: false },
    { id: "client-field-notes", name: "Field Notes", company: "Field Notes", contactName: "", email: "", phone: "", notes: "", archived: false },
    { id: "client-orbit-labs", name: "Orbit Labs", company: "Orbit Labs", contactName: "", email: "", phone: "", notes: "", archived: false },
  ],
  customProjectTemplates: [],
  projectTags: ["Client Work", "Retainer", "Personal Channel"],
  salaryWorkType: "Retainer",
  salaryBatchSize: 20,
  salaryBatchAmount: 10000,
  projectStages: ["Planned", "In Progress", "Client Review", "Delivered"],
  notifications: {},
  integrations: {},
  integrationAccounts: {},
  integrationConfigs: {},
  integrationLinks: {},
  teamRole: "Owner",
  teamMembers: [],
  editorPermissions: {},
  rolePermissions: {},
    theme: "Dark",
    accentColor: "#14B8A6",
  density: "Comfortable",
};

export const sampleStudioProjects: WorkItem[] = [
  {
    id: "sample-launch-film",
    profileId: "video-editor",
    createdAt: "2026-07-18T08:30:00.000Z",
    title: "Summer launch film",
    client: "Aperture Coffee",
    status: "In Progress",
    workType: "Client Work",
    startDate: "2026-07-18",
    dueDate: "2026-07-24",
    earnings: 1800,
    notes: "Picture lock is due next. Sound mix and final captions follow after approval.",
    workflowStages: ["Assembly", "Fine cut", "Client Review", "Delivery"],
    checklistItems: ["Organize selects", "Complete fine cut", "Send review link", "Export masters"],
    checklistCompleted: { "Organize selects": true, "Complete fine cut": true },
  },
  {
    id: "sample-founder-story",
    profileId: "video-editor",
    createdAt: "2026-07-14T10:15:00.000Z",
    title: "Founder story cutdown",
    client: "Orbit Labs",
    status: "Client Review",
    workType: "Client Work",
    startDate: "2026-07-14",
    dueDate: "2026-07-23",
    earnings: 950,
    notes: "Review link sent. Client requested a tighter opening and one lower-third correction.",
    workflowStages: ["Assembly", "Fine cut", "Client Review", "Delivery"],
    checklistItems: ["Build first cut", "Internal review", "Send client review", "Address notes"],
    checklistCompleted: { "Build first cut": true, "Internal review": true, "Send client review": true },
  },
  {
    id: "sample-field-notes",
    profileId: "video-editor",
    createdAt: "2026-07-04T07:45:00.000Z",
    title: "Field Notes episode 12",
    client: "Field Notes",
    status: "Delivered",
    workType: "Client Work",
    startDate: "2026-07-04",
    dueDate: "2026-07-11",
    earnings: 1200,
    paid: true,
    paidDate: "2026-07-15T12:00:00.000Z",
    notes: "Approved on the second review round. Master and social cutdowns delivered.",
    checklistItems: ["Edit episode", "Client approval", "Deliver master", "Confirm payment"],
    checklistCompleted: { "Edit episode": true, "Client approval": true, "Deliver master": true, "Confirm payment": true },
  },
];

export const sampleStudioResources: ResourceLink[] = [
  {
    id: "sample-review-link",
    title: "Client review example",
    url: "/client-portal",
    category: "Review",
    projectId: "sample-founder-story",
    notes: "Clients open a private editor-provided link and do not need a Relay account.",
    createdAt: "2026-07-21T09:00:00.000Z",
    updatedAt: "2026-07-21T09:00:00.000Z",
  },
];
